---
- name: add backup-networkmanager cron.daily
  become: yes
  ansible.builtin.copy:
    src: "/home/{{ current_user }}/.dotfiles/_backup/cron.daily/backup-networkmanager-cron.sh"
    dest: "/etc/cron.daily/backup-networkmanager-cron.sh"
    owner: "root"
    group: "root"
    mode: "0644"
- name: replace current_user backup-networkmanager cron.daily
  become: yes
  ansible.builtin.replace:
    path: "/etc/cron.daily/backup-networkmanager-cron.sh"
    regexp: ":CURRENT_USER:"
    replace: "{{ current_user }}"
