---
- name: prepare for ttf-mscorefonts auto install
  become: yes
  shell: "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
- name: install ubuntu base packages
  become: yes
  apt:
    package:
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras
      - apt-file
      - aptitude
      - flatpak
      - inotify-tools
      - inxi
      - libfuse2 # for appimage
    state: latest
- name: install deb fonts
  become: yes
  apt:
    package:
      - fonts-alee
      - fonts-lexi-gulim
      - fonts-lexi-saebom
      - fonts-woowa-bm
      - fonts-nanum
      - fonts-nanum-eco
      - fonts-nanum-extra
      - fonts-naver-d2coding
      - fonts-unfonts-core
      - fonts-unfonts-extra
      - fonts-pretendard
      - fonts-noto-cjk
      - fonts-noto-cjk-extra
      - ttf-mscorefonts-installer
      - fonts-croscore # Chrome OS core fonts
      - fonts-crosextra-carlito # Chrome OS core extra - MS Calibri 대체
      - fonts-crosextra-caladea # Chrome OS core extra - MS Cambria 대체
    state: latest
- name: install utils
  become: yes
  apt:
    package:
      - lsd
      - ripgrep
      - fd-find
      - tmux
      - xclip
      - htop
      - btop
      - bpytop
      - stacer
      - cpufrequtils
      - most
      - direnv
      - autojump
      - stow
      - rclone
      - krusader
      - trash-cli
      - ncdu
      - bat
      - timeshift
      - ranger
      - convmv
      - nq
      - cpulimit
      - httpie
      - keyutils
      - cowsay
      - lolcat
      - gnome-multi-writer
      - bd
      - jq
      - jc
      - iotop
      - atop
      - guake
      - python3-argcomplete # ansible bash auto completion
      - urlview # for tmux urlview
      - xpad # sticky note
      - transmission-qt
      - intel-gpu-tools
      - ksnip # for image/screenshot annotation
      - adb # for android development and scrcpy
      - poppler-utils # pdf utils
    state: latest
- name: install remove unused utils
  become: yes
  apt:
    package:
      - transmission-gtk
    state: absent
- name: install system tools
  become: yes
  apt:
    package:
      - powertop
      - mainline
      - gparted
      - dconf-editor
      - blueman
      - grub-customizer
    state: latest
- name: install development base tools
  become: yes
  apt:
    package:
      - kdialog
      - zenity
      - universal-ctags
      - java-common
      - openjdk-17-jdk
      - openjdk-17-source
      - openjdk-11-jdk
      - openjdk-11-source
      - openjdk-8-jdk
      - openjdk-8-source
      - build-essential
      - dkms
      - make
      - cmake
      - git-flow
      - tig
      - meld
      - python3-pip
      - shellcheck
      - rabbitvcs-nautilus
      - rabbitvcs-cli
    state: latest
- name: update-alternatives java # java 11을 기본으로. java 17 아직 지원안하는 애플리케이션이 많음.
  become: yes
  shell: |
    update-alternatives --set java  /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
- name: install network tools
  become: yes
  apt:
    package:
      - inxi
      - neowofetch
      - ufw
      - gufw
      - openconnect
      - net-tools
      - smbclient
      - network-manager-openconnect
      - openfortivpn
      - network-manager-fortisslvpn
      - openssh-client
      - freerdp2-x11
      - openssh-server
      - openssh-sftp-server
      - sshpass
      - putty
      - putty-tools
      - filezilla
    state: latest
- name: install remote desktop
  become: yes
  apt:
    package:
      - remmina
      - remmina-plugin-spice
      - remmina-plugin-x2go
      - remmina-plugin-vnc
      - remmina-plugin-rdp
    state: latest
- name: install system-monitor-next extension dependencies
  become: yes
  apt:
    package:
      - gir1.2-gtop-2.0
      - gir1.2-nm-1.0
      - gir1.2-clutter-1.0
      - gnome-system-monitor
- name: install editors
  become: yes
  apt:
    package:
      - nano
      - micro
      - vim-nox
      - vim-gtk3
      - geany
      - geany-plugins
    state: latest
- name: install input methods
  become: yes
  apt:
    package:
      - ibus
      - ibus-hangul
    state: latest
- name: flatpak add remote flathub
  become: yes
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
- name: apt clean # ansible의 autoclean 은 clean이 아니다.
  become: yes
  ansible.builtin.command: apt clean
- name: ibus config
  shell: |
    # for gnome disable ibus, 의존성 때문에 패키지 삭제가 불가해서 실행만 안되게 이름변경. 아래 작업을 안하면 uim/ibus 동시 사용가능해짐
    # gnome 자체는 ibus 를 사용하고, 나머지는 uim 사용하게 복합 설정
    gsettings set org.gnome.settings-daemon.plugins.keyboard active true
    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'ibus'>}"
    # ibus 한글 관련 설정
    gsettings set org.freedesktop.ibus.engine.hangul auto-reorder true
    gsettings set org.freedesktop.ibus.engine.hangul hangul-keyboard '39'
    gsettings set org.freedesktop.ibus.engine.hangul initial-input-mode 'latin'
    gsettings set org.freedesktop.ibus.engine.hangul hanja-keys 'Hangul_Hanja,F9'
    gsettings set org.freedesktop.ibus.engine.hangul switch-keys 'Hangul,Shift+space'
    gsettings set org.freedesktop.ibus.engine.hangul word-commit false
    # emoji,unicode 입력 단축키 변경
    gsettings set org.freedesktop.ibus.panel.emoji font "Noto Color Emoji 16"
    gsettings set org.freedesktop.ibus.panel.emoji hotkey "['<Shift><Super>e']"
    gsettings set org.freedesktop.ibus.panel.emoji unicode-hotkey "[]"

    # preedit-mode 는 원래 syllable 인데, word로 변경하면, chromium/electron 계열에서 한글입력이 잘된다.
    gsettings set org.freedesktop.ibus.engine.hangul preedit-mode 'word'

    # zoom 등 옛날 QT 라이브러리로 된 프로그램에서 backspace, arrow 키 잘 안먹는 문제 해결하려면 이 값을 false로 변경한다.
    # 그러나 현재 zoom 외에는 이 값이 true 인게 잘 작동한다. zoom 사용할 때만 일시적으로 false로 변경할 것.
    # $HOME/.local/bin/ibus-toggle-use-event-forwarding.sh 사용
    gsettings set org.freedesktop.ibus.engine.hangul use-event-forwarding true

    # 한영키 xkb, ibus 관련 설정
    gsettings set org.gnome.desktop.input-sources xkb-options "['korean:ralt_hangul', 'korean:rctrl_hanja']"

    # gsettings set org.gnome.settings-daemon.plugins.keyboard active false
    # gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'uim'>}"
    # sudo mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.distrib
- name: set default im
  shell: "im-config -n ibus"
- name: tmux plugin manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "/home/{{ current_user }}/.tmux/plugins/tpm"
