---
- name: prepare for virtualbox-ext-pack PUEL accept # https://askubuntu.com/questions/811488/command-to-accept-virtualbox-puel-for-virtualbox-ext-pack-installation
  become: yes
  shell: "echo virtualbox-ext-pack virtualbox-ext-pack/license select true | debconf-set-selections"
- name: install virtualization
  become: yes
  apt:
    package:
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
- name: install node.js # vim markdown plugin에 필요함.
  become: yes
  apt:
    package:
      - nodejs
      - npm
      - yarnpkg
- name: install vscode
  become: yes
  apt:
    package:
      - code
    state: latest
- name: database clients
  become: yes
  apt:
    package:
      - mysql-client
    state: latest
- name: zoom.us install
  ansible.builtin.command: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-zoom.sh"
- name: google chrome install
  become: yes
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  register: google_chrome_installed
  until: google_chrome_installed is not failed
  retries: 3
  delay: 10
- name: Slack
  become: yes
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.33.90/prod/x64/slack-desktop-4.33.90-amd64.deb
  register: slack_installed
  until: slack_installed is not failed
  retries: 3
  delay: 10
- name: bitwarden
  community.general.flatpak:
    name: "com.bitwarden.desktop"
  register: bitwarden_installed
  until: bitwarden_installed is not failed
  retries: 3
  delay: 10
- name: joplin
  community.general.flatpak:
    name: "net.cozic.joplin_desktop"
  register: joplin_installed
  until: joplin_installed is not failed
  retries: 3
  delay: 10
- name: local applications dir
  file:
    path: "/home/{{ current_user }}/.local/share/applications"
    state: directory
- name: Memory Analyzer(MAT)
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-mat.sh"
- name: Java Mission Control
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-jmc.sh"
- name: ulauncher
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-ulauncher.sh"
- name: nerd-fonts
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-nerd-fonts.sh"
- name: docker-compose
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-docker-compose.sh"
- name: wrappers-easy-executor
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-wrappers-easy-executor.sh"
- name: IntelliJ IDEA target dir
  file:
    path: "/home/{{ current_user }}/.local/opt/JetBrains/ideaIU"
    state: directory
- name: intellij ultimate latest version
  shell: curl -fsSL "https://data.services.jetbrains.com/products?code=IIU%2CIIC&release.type=release" | jq -r '[.[].releases[].version][0]'
  register: jetbrains_intellij_idea_latest_version_result
- set_fact:
    jetbrains_intellij_idea_latest_version={{ jetbrains_intellij_idea_latest_version_result.stdout }}
- name: IntelliJ IDEA user install
  unarchive: # https://download-cdn.jetbrains.com/idea/ideaIU-2022.1.3.tar.gz
    src: "https://download-cdn.jetbrains.com/idea/ideaIU-{{ jetbrains_intellij_idea_latest_version }}.tar.gz"
    remote_src: yes
    dest: "/home/{{current_user}}/.local/opt/JetBrains/ideaIU"
    extra_opts: [--strip-components=1]
    creates: "/home/{{ current_user }}/.local/opt/JetBrains/ideaIU/bin/idea.sh"
  register: intellij_idea_installed
  until: intellij_idea_installed is not failed
  retries: 3
  delay: 10
