---
- name: prepare for virtualbox-ext-pack PUEL accept # https://askubuntu.com/questions/811488/command-to-accept-virtualbox-puel-for-virtualbox-ext-pack-installation
  become: yes
  shell: "echo virtualbox-ext-pack virtualbox-ext-pack/license select true | debconf-set-selections"
- name: install virtualization
  become: yes
  apt:
    package:
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
- name: install node.js # vim markdown plugin에 필요함.
  become: yes
  apt:
    package:
      - nodejs
      - npm
      - yarnpkg
- name: install vscode
  become: yes
  apt:
    package:
      - code
    state: latest
- name: install vagrant
  become: yes
  apt:
    package:
      - vagrant
    state: latest
- name: install packer
  become: yes
  apt:
    package:
      - packer
    state: latest
- name: database clients
  become: yes
  apt:
    package:
      - mysql-client
    state: latest
- name: zoom.us preparation
  become: yes
  apt:
    package:
      - libgl1-mesa-glx
      - libegl1-mesa
      - libxcb-xtest0
    state: latest
- name: zoom.us install
  ansible.builtin.command: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-zoom.sh"
- name: google chrome install
  become: yes
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  register: google_chrome_installed
  until: google_chrome_installed is not failed
  retries: 3
  delay: 10
- name: Slack
  community.general.flatpak:
    name: "com.slack.Slack"
  register: slack_installed
  until: slack_installed is not failed
  retries: 3
  delay: 10
- name: IntelliJIDEA
  community.general.snap: # intellij는 snap 버전이 더 잘 작동하고 관리가 잘됨
    name: intellij-idea-ultimate
    classic: true
    state: present
  register: intellij_idea_installed
  until: intellij_idea_installed is not failed
  retries: 3
  delay: 10
- name: bitwarden
  community.general.flatpak:
    name: "com.bitwarden.desktop"
  register: bitwarden_installed
  until: bitwarden_installed is not failed
  retries: 3
  delay: 10
- name: joplin
  community.general.flatpak:
    name: "net.cozic.joplin_desktop"
  register: joplin_installed
  until: joplin_installed is not failed
  retries: 3
  delay: 10
- name: Flameshot
  community.general.flatpak:
    name: "org.flameshot.Flameshot"
  register: flameshot_installed
  until: flameshot_installed is not failed
  retries: 3
  delay: 10
- name: local applications dir
  file:
    path: "/home/{{ current_user }}/.local/share/applications"
    state: directory
- name: Memory Analyzer(MAT)
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-mat.sh"
- name: Java Mission Control
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-jmc.sh"
- name: ulauncher
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-ulauncher.sh"
- name: nerd-fonts
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-nerd-fonts.sh"
- name: docker-compose
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-docker-compose.sh"
- name: wrappers-easy-executor
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-wrappers-easy-executor.sh"
