---
- name: virt-manager
  become: yes
  apt:
    package:
      - virt-manager
      - libvirt-daemon
      - qemu-system-x86
      - libvirt-dev # for vagrant libvirt provider
- name: prepare for virtualbox-ext-pack PUEL accept # https://askubuntu.com/questions/811488/command-to-accept-virtualbox-puel-for-virtualbox-ext-pack-installation
  become: yes
  shell: "echo virtualbox-ext-pack virtualbox-ext-pack/license select true | debconf-set-selections"
- name: install virtualization
  become: yes
  apt:
    package:
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
- name: virtualbox usergroup
  become: yes
  ansible.builtin.user:
    name: "{{ current_user }}"
    groups: vboxusers
    append: yes
- name: install node.js # vim markdown plugin에 필요함.
  become: yes
  apt:
    package:
      - nodejs
      - npm
      - yarnpkg
- name: install vscode
  become: yes
  apt:
    package:
      - code
    state: latest
- name: database clients
  become: yes
  apt:
    package:
      - mysql-client
    state: latest
- name: google chrome install
  become: yes
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  register: google_chrome_installed
  until: google_chrome_installed is not failed
  retries: 3
  delay: 10
- name: naver whale install
  become: yes
  apt:
    deb: https://installer-whale.pstatic.net/downloads/installers/naver-whale-stable_amd64.deb
  register: naver_whale_installed
  until: naver_whale_installed is not failed
  retries: 3
  delay: 10
  when: 0 > 1 # apt-key deprecation 으로 설치에 문제가 생김. disable
- name: Slack
  become: yes
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.33.90/prod/x64/slack-desktop-4.33.90-amd64.deb
  register: slack_installed
  until: slack_installed is not failed
  retries: 3
  delay: 10
- name: bitwarden
  community.general.flatpak:
    name: "com.bitwarden.desktop"
  register: bitwarden_installed
  until: bitwarden_installed is not failed
  retries: 3
  delay: 10
- name: multipass
  become: yes
  community.general.snap:
    channel: stable
    name: multipass
- name: multipass connect
  become: yes
  shell: |
    snap connect multipass:firewall-control snapd:firewall-control
    snap connect multipass:multipass-support snapd:multipass-support
- name: local applications dir
  file:
    path: "/home/{{ current_user }}/.local/share/applications"
    state: directory
- name: Memory Analyzer(MAT)
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-mat.sh"
- name: Java Mission Control
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-jmc.sh"
- name: ulauncher
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-ulauncher.sh"
- name: docker-compose
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-docker-compose.sh"
- name: wrappers-easy-executor
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-wrappers-easy-executor.sh"
- name: install jetbrains toolbox
  shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-jetbrains-toolbox.sh"
  args:
    creates: "/home/{{ current_user }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
  register: jetbrains_toolbox_installed
  until: jetbrains_toolbox_installed is not failed
  retries: 3
  delay: 3
