---
- name: install docker
  become: yes
  apt:
    package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - ctop
    state: latest
- name: docker group
  become: yes
  ansible.builtin.group:
    name: docker
    state: present
- name: add user to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ current_user }}"
    groups:
      - docker
    append: yes
- name: docker systemd enable
  become: yes
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
- name: containerd systemd enable
  become: yes
  ansible.builtin.systemd:
    name: containerd.service
    enabled: yes
