---
- name: install docker
  become: yes
  apt:
    package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-ce-rootless-extras
    state: latest
- name: docker group # rootless 를 사용하면서 불필요해짐.
  become: yes
  ansible.builtin.group:
    name: docker
    state: present
  when: false
- name: add user to docker group # rootless 를 사용하면서 불필요해짐.
  become: yes
  ansible.builtin.user:
    name: "{{ current_user }}"
    groups:
      - docker
    append: yes
  when: false
- name: docker systemd disable for rootless
  become: yes
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: false
    state: stopped
- name: docker socket systemd disable for rootless
  become: yes
  ansible.builtin.systemd_service:
    name: docker.socket
    enabled: false
    state: stopped
- name: containerd systemd enable
  become: yes
  ansible.builtin.systemd_service:
    name: containerd.service
    enabled: true
- name: docker rootless setup
  ansible.builtin.shell: /usr/bin/dockerd-rootless-setuptool.sh install
- name: docker  rootless enable user systemd
  become: yes
  ansible.builtin.shell: loginctl enable-linger "{{ current_user }}"
- name: docker user systemd enable for rootless
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    scope: user
