---
- name: extra package install yml
  hosts: 127.0.0.1, localhost
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: install virtualization
      become: yes
      apt:
        package:
          - virtualbox
          - virtualbox-guest-additions-iso
          - qemu
          - aqemu
          - qemu-kvm
          - virt-manager
    - name: install video audio graphic packages
      become: yes
      apt:
        package:
          - gimp
          - gimp-gmic
          - gimp-data-extras
          - gimp-help-ko
          - nomacs
          - sxiv
          - vlc
          - smplayer
          - audacious
          - kdenlive
          - handbrake
          - gpick
    - name: install extra dev related packages
      become: yes
      apt:
        package:
          - vagrant
            #- asbru-cm
          - unetbootin
          - gh
          - code
          - packer
          - terraform
    - name: database clients
      become: yes
      apt:
        package:
          - mysql-client
    - name: add architecture i386
      become: yes
      shell: "dpkg --add-architecture i386"
    - name: install wine & playonlinux
      become: yes
      apt:
        package:
          - wine
          - winetricks
          - playonlinux
    - name: install rust and cargo
      become: yes
      apt:
        package:
          - rustc
          - cargo
    - name: ocs-url dependencies
      become: yes
      apt:
        package:
          - libqt5svg5
          - qml-module-qtquick-controls
    - name: ocs-url install # https://www.opendesktop.org/p/1136805/
      become: yes
      apt:
        deb: "/home/{{ current_user }}/.dotfiles/_backup/themes/ocs-url_3.1.0-0ubuntu1_amd64.deb"
    - name: zoom.us preparation
      become: yes
      apt:
        package:
          - libgl1-mesa-glx
          - libegl1-mesa
          - libxcb-xtest0
    - name: zoom.us install
      command: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/zoom-install.sh"
    - name: dbeaver install
      command: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/dbeaver-ce-install.sh"
    - name: download DEBs install
      become: yes
      apt:
        deb: "{{ item }}"
      register: download_debs_installed
      until: download_debs_installed is not failed
      retries: 3
      delay: 10
      with_items:
        - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb"
        - "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_{{ hugo_version }}_Linux-64bit.deb"
        - "https://github.com/muesli/duf/releases/download/v0.4.0/duf_{{ duf_version }}_linux_amd64.deb"
    - name: youtube-dl
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/youtube-dl-download.sh"
    - name: newsflash rss reader
      flatpak:
        name: "com.gitlab.newsflash"
    - name: bitwarden
      flatpak:
        name: "com.bitwarden.desktop"
    - name: local applications dir
      file:
        path: "/home/{{ current_user }}/.local/share/applications"
        state: directory
    - name: IntelliJ IDEA target dir
      file:
        path: "/home/{{ current_user }}/.local/opt/JetBrains/ideaIU"
        state: directory
    - name: IntelliJ IDEA user install
      unarchive:
        src: "https://download.jetbrains.com/idea/ideaIU-{{ jetbrains_intellij_idea_version }}.tar.gz"
        remote_src: yes
        dest: "/home/{{current_user}}/.local/opt/JetBrains/ideaIU"
        extra_opts: [--strip-components=1]
        creates: "/home/{{ current_user }}/.local/opt/JetBrains/ideaIU/bin/idea.sh"
      register: intellij_idea_installed
      until: intellij_idea_installed is not failed
      retries: 3
      delay: 10
    - name: Memory Analyzer(MAT)
      unarchive:
        src: http://mirror.kakao.com/eclipse/mat/1.10.0/rcp/MemoryAnalyzer-1.10.0.20200225-linux.gtk.x86_64.zip
        remote_src: yes
        dest: "/home/{{ current_user }}/.local/opt"
        creates: "/home/{{ current_user }}/.local/opt/mat"
    - name: fzf
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-fzf.sh"
    - name: fblog
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-fblog.sh"
    - name: sd
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-sd.sh"
    - name: broot
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-broot.sh"
    - name: dust
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-dust.sh"
    - name: lazydocker
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-lazydocker.sh"
    - name: bitwarden-cli
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-bitwarden-cli.sh"
    - name: bpytop
      become: yes
      community.general.snap:
        name:
          - bpytop
        state: present
    - name: bpytop permissions
      become: yes
      shell: |
        snap connect bpytop:mount-observe
        snap connect bpytop:network-control
        snap connect bpytop:hardware-observe
        snap connect bpytop:system-observe
        snap connect bpytop:process-control
        snap connect bpytop:physical-memory-observe
