---
# 당장 개발에 필수는 아닌 애플리케이션들 설치
- name: main
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/home/linuxbrew/.linuxbrew/bin"
  tasks:
    - name: install KDE/GNOME themes
      become: yes
      apt:
        install_recommends: yes
        package:
          - papirus-icon-theme
          - papirus-folders
          - materia-gtk-theme
          - materia-kde
          - arc-theme
          - dmz-cursor-theme
          - xcursor-themes
          - numix-blue-gtk-theme
          - numix-gtk-theme
          - numix-icon-theme-circle
          - numix-icon-theme
        state: latest
    - name: install libreoffice
      become: yes
      apt:
        package:
          - libreoffice
          - libreoffice-help-ko
          - libreoffice-l10n-ko
          - libreoffice-style-*
          - libreoffice-sdbc-*
        state: latest
    - name: install wallpapers
      become: yes
      apt:
        package:
          - ubuntu-wallpapers-*
          - gnome-backgrounds
        state: latest
    - name: install GIMP
      become: yes
      apt:
        package:
          - gimp
          - gimp-gmic
          - gimp-data-extras
          - gimp-help-ko
        state: latest
    - name: install video audio graphic packages
      become: yes
      apt:
        package:
          - gimp
          - gimp-gmic
          - gimp-data-extras
          - gimp-help-ko
          - nomacs
          - sxiv
          - vlc
          - smplayer
          - audacious
          - handbrake
          - gpick
          - gromit-mpx
        state: latest
    - name: add architecture i386
      become: yes
      shell: "dpkg --add-architecture i386"
    - name: install wine & playonlinux
      become: yes
      apt:
        package:
          - wine
          - winetricks
          - playonlinux
        state: latest
    - name: ocs-url dependencies
      become: yes
      apt:
        package:
          - libqt5svg5
          - qml-module-qtquick-controls
        state: latest
    - name: ocs-url install # https://www.opendesktop.org/p/1136805/
      become: yes
      apt:
        deb: "/home/{{ current_user }}/.dotfiles/_backup/themes/ocs-url_3.1.0-0ubuntu1_amd64.deb"
    - name: shotcut
      community.general.flatpak:
        name: "org.shotcut.Shotcut"
    - name: flatseal
      community.general.flatpak:
        name: "com.github.tchx84.Flatseal"
    - name: blanket
      community.general.flatpak:
        name: "com.rafaelmardojai.Blanket"
    - name: OTPClient
      community.general.flatpak:
        name: "com.github.paolostivanin.OTPClient"
    - name: fluentreader
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-fluentreader.sh"
    - name: dbeaver-ce
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-dbeaver-ce.sh"
    - name: balena-etcher
      shell: "/home/{{ current_user }}/.dotfiles/local_bin/.local/bin/install-etcher_appimage.sh"
    - name: ascii-image-converter
      become: yes
      community.general.snap:
        name: ascii-image-converter
        state: present
    - name: dirsize # https://github.com/frossm/dirsize
      become: yes
      community.general.snap:
        name: dirsize
        state: present
    - name: diresize permission
      become: yes
      shell: |
        snap connect dirsize:system-backup
    - name: download meganz
      become: yes
      apt:
        deb: "{{ item }}"
      register: meganz_debs_installed
      until: meganz_debs_installed is not failed
      retries: 3
      delay: 10
      with_items:
        - "https://mega.nz/linux/MEGAsync/xUbuntu_{{ ubuntu_version }}/amd64/megacmd-xUbuntu_{{ ubuntu_version }}_amd64.deb"
        - "https://mega.nz/linux/MEGAsync/xUbuntu_{{ ubuntu_version }}/amd64/megasync-xUbuntu_{{ ubuntu_version }}_amd64.deb"
    - name: update apt cache all
      become: yes
      apt:
        update_cache: yes
        state: fixed
    - name: install mega apps
      become: yes
      apt:
        package:
          - megadown
          - megatools
          - nautilus-megasync
        state: latest
