---
- name: common package installation
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: ufw config
      become: yes
      shell: |
        ufw enable
        ufw default deny incoming
        ufw default allow outgoing
        ufw allow ssh
        ufw allow 8999 # for qbittorrent
