---
- name: install GNOME packages
  become: yes
  apt:
    package:
      - synaptic
      - gdebi
      - gnome-tweaks
      - gnome-clocks
      - alacarte
      - gnome-authenticator
      - python3-pydrive2 # for deja-dup
      - deja-dup
      - gnome-clocks
      - gnome-calendar
    state: latest
- name: install nautilus packages
  become: yes
  apt:
    package:
      - nautilus-admin
      - gnome-sushi
      - nautilus-image-converter
      - nautilus-script-manager
      - nautilus-share
    state: latest
- name: install GNOME network packages
  become: yes
  apt:
    package:
      - network-manager-fortisslvpn-gnome
      - network-manager-openconnect-gnome
      - network-manager-openvpn-gnome
    state: latest
- name: install libsecret packages
  become: yes
  apt:
    package:
      - seahorse
      - libsecret-1-0
      - libsecret-1-dev # for git credential
    state: latest
- name: install shell extensions packages
  become: yes
  apt:
    package:
      - gnome-browser-connector
      - gnome-shell-extension-prefs
      - gnome-shell-extensions
      - gnome-shell-extension-manager
      - gnome-shell-pomodoro
    state: latest
- name: install qt themes
  become: yes
  apt:
    package:
      - qt6-style-kvantum # for qt5 theme
      - qt6-style-kvantum-l10n # for qt5 theme
      - qt6-style-kvantum-themes # for qt5 theme
      - qt6ct # for qt5 theme
      - breeze
    state: latest
- name: build git libsecret git credential helper
  become: yes
  shell: |
    cd /usr/share/doc/git/contrib/credential/libsecret
    make
- name: install gnome-extensions-cli
  shell: |
    pipx install gnome-extensions-cli
- name: install gnome extensions
  shell: |
    $HOME/.local/bin/gext install {{ item }}
    # 아래는 gext 로 설치시 gschemas.compiled 가 생성 안되는 버그 때문에 필요. 버그 해소시 불필요함.
    if [ -d "$HOME/.local/share/gnome-shell/extensions/{{ item }}/schemas" ]; then
      echo "> compile {{ item }} schemas...."
      glib-compile-schemas "$HOME/.local/share/gnome-shell/extensions/{{ item }}/schemas"
    fi
    echo "재 로그인 후에 gnome extension 들이 활성화 됨"
  with_items:
    - "bluetooth-quick-connect@bjarosze.gmail.com"
    - "caffeine@patapon.info"
    - "clipboard-indicator@tudmotu.com"
    - "ddterm@amezin.github.com"
    - "desktop-cube@schneegans.github.com"
    - "do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com"
    - "gsconnect@andyholmes.github.io"
    - "Move_Clock@rmy.pobox.com"
    - "nothing-to-say@extensions.gnome.wouter.bolsterl.ee"
    - "panel-date-format@keiii.github.com"
    - "status-area-horizontal-spacing@mathematical.coffee.gmail.com"
- name: fix ddterm binary executable
  ansible.builtin.file:
    path: "/home/{{ current_user }}/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm"
    mode: "0755"
