---
- name: create grub theme directory
  become: yes
  file:
    path: /boot/grub/themes
    state: directory
- name: install grub custom themes
  become: yes
  unarchive:
    src: ~/.dotfiles/_backup/grub-themes/{{ item }}
    dest: /boot/grub/themes
  with_items:
    - tela-4k.tar.gz
    - tela-1k.tar.gz
    - vimix-4k.tar.gz
    - vimix-1k.tar.gz
- name: grub customize gfxmode
  become: yes
  ansible.builtin.lineinfile: /etc/default/grub
    line: GRUB_GFXMODE="1920x1080x32"
- name: grub customize 1k theme
  become: yes
  ansible.builtin.lineinfile: /etc/default/grub
    line: GRUB_THEME="/boot/grub/themes/tela-1k/theme.txt"
- name: grub customize apply
  become: yes
  shell:
  args:
    cmd: update-grub
