---
- name: install grub2 theme
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  become: yes
  tasks:
    - name: create theme directory
      file:
        path: /boot/grub/themes
        state: directory
    - name: install grub custom themes
      unarchive:
        src: ~/.dotfiles/_backup/grub-themes/{{ item }}
        dest: /boot/grub/themes
      with_items:
        - tela-4k.tar.gz
        - tela-1k.tar.gz
        - vimix-4k.tar.gz
        - vimix-1k.tar.gz
