---
# https://kwonnam.pe.kr/wiki/linux/hidpi
- name: 4k monitor config
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: console 4k font
      become: yes
      shell: |
        sed -i.bak1k -e "s/^CODESET/#CODESET/g" \
          -e "s/^FONTFACE/#FONTFACE/g" \
          -e "s/^FONTSIZE/#FONTSIZE/g" \
          /etc/default/console-setup
      args:
        creates: /etc/default/console-setup.bak1k
    - name: console 4k font add lines
      become: yes
      blockinfile:
        path: /etc/default/console-setup
        block: |
          CODESET="Uni3"
          FONTFACE="Terminus"
          FONTSIZE="32x16"
    - name: grub font to Nanum Gothic Coding
      become: yes
      shell: |
        mkdir -p /boot/grub/fonts
        grub-mkfont --output=/boot/grub/fonts/NanumGothicCoding32.pf2 --size=32 /usr/share/fonts/truetype/nanum/NanumGothicCoding.ttf
        echo 'GRUB_FONT="/boot/grub/fonts/NanumGothicCoding32.pf2"' >> /etc/default/grub.d/99_fonts.cfg
        update-grub
