---
- name: install linux Homebrew
  shell: # echo for bypassing prompt
  args:
    cmd: echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_installed
  until: brew_installed is not failed
  retries: 5
  delay: 10
- name: update homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
- name: brew common packages
  community.general.homebrew:
    name:
      - neovim
      - neovim-remote
      - lazygit
      - lazydocker
      - fblog
      - fzf
      - sd
      - duf
      - broot
      - go-jira
      - bitwarden-cli
      - youtube-dl
      - dust
      - procs
      - hugo
      - speedread
      - tfenv
      - yq
      - git-delta
      - bpytop
      - awscli
      - eksctl
      - minikube
      - kubectl
      - starship
      - exa # ubuntu 기본 버전에 문제가 있음. brew 로 설치
    state: present
  register: brew_common_packages
  until: brew_common_packages is not failed
  retries: 3
  delay: 10
- name: tfenv-init
  shell: |
    tfenv install latest
    tfenv use latest
  args:
    executable: /usr/bin/bash
