---
- name: HomeBrew and install brew packages
  hosts: 127.0.0.1, localhost
  connection: local
  vars_files:
    - "vars.yml"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/home/linuxbrew/.linuxbrew/bin"
  tasks:
    - name: install linux HomeBrew
      shell: # echo for bypassing prompt
      args:
        cmd: echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        creates: /home/linuxbrew/.linuxbrew/bin/brew
      register: brew_installed
      until: brew_installed is not failed
      retries: 5
      delay: 10
    - name: update homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
    - name: brew common packages
      homebrew:
        name:
          - fzf # fzf apt 버전이 낮아서 brew로 설치
          - fblog
          - lazygit
          - lazydocker
          - jvmtop
          - sd
          - zenith
          - bitwarden-cli
          - broot
          - tgotwig/linux-dust/dust
          - hashicorp/tap/terraform
          - hashicorp/tap/packer
        state: present
      register: brew_common_packages
      until: brew_common_packages is not failed
      retries: 3
      delay: 10
