---
- name: install linux Homebrew
  shell: # echo for bypassing prompt
  args:
    cmd: echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_installed
  until: brew_installed is not failed
  retries: 5
  delay: 10
- name: brew bundle install
  shell: "/home/linuxbrew/.linuxbrew/bin/brew bundle --file=/home/{{ current_user }}/.dotfiles/_backup/brew/Brewfile"
  args:
    executable: /usr/bin/bash
  register: brew_bundle
  until: brew_bundle is not failed
  retries: 3
  delay: 10
