---
- name: main
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: jenkins key
      become: yes
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      register: jenkins_repo_key_installed
      until: jenkins_repo_key_installed is not failed
      retries: 3
    - name: jenkins repo
      become: yes
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        filename: jenkins
        update_cache: yes
    - name: install jenkins replated packages
      become: yes
      apt:
        package:
          - openjdk-11-jdk
          - jenkins
    - name: change jenkins user
      become: yes
      shell: |
        systemctl stop jenkins

        # Java 1.8, 11만 지원함. systemctl 로 실행할 경우 JAVA_HOME을 지정할 수 있는 방법이 없음.
        # 기본적으로 시스템 전역 Java 를 Java 8 or 11로 강제 지정해두어야함.
        # see /etc/init.d/jenkins
        # see  common_package_install_tasks.yml update-alternatives java
        sed -i.bak -e "s/JENKINS_USER=\$NAME/JENKINS_USER={{ current_user }}/g" \
            -e "s/JENKINS_GROUP=\$NAME/JENKINS_GROUP={{ current_user }}/g" \
            -e "s/HTTP_PORT=8080/HTTP_PORT=9999/g" \
            /etc/default/jenkins

        mkdir -p /var/lib/jenkins/init.groovy.d

        cp /home/{{ current_user }}/.dotfiles/_backup/jenkins/init_admin.groovy /var/lib/jenkins/init.groovy.d/

        chown -R {{ current_user }}:{{ current_user }} /var/lib/jenkins
        chown -R {{ current_user }}:{{ current_user }} /var/cache/jenkins
        chown -R {{ current_user }}:{{ current_user }} /var/log/jenkins

        systemctl start jenkins
