---
- name: install KDE only packages
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: install KDE packages
      become: yes
      apt:
        package:
          - kubuntu-restricted-addons
          - kubuntu-restricted-extras
          - muon
          - qapt-deb-installer
          - plasma-discover-backend-flatpak
          - plasma-discover-backend-fwupd
          - yakuake
          - dolphin-plugins
          - kio-gdrive
          - plasma-browser-integration
          - kwalletcli
          - qttools5-dev-tools # for qdbusviewer
          - kmix # kubuntu 20.10 에서 자동설치 안됐음
    - name: install KDE/GNOME themes
      become: yes
      apt:
        install_recommends: yes
        package:
          - papirus-icon-theme
          - materia-kde
          - papirus-folders
          - materia-gtk-theme
          - arc-theme
          - dmz-cursor-theme
    - name: change lookandfeel
      shell: |
        lookandfeeltool --apply com.github.varlesh.materia
        qdbus org.kde.GtkConfig /GtkConfig setGtk3Theme Materia-dark
        qdbus org.kde.GtkConfig /GtkConfig setGtk2Theme Materia-dark
