---
- name: KDE local user configuration
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: kde dirs
      file:
        path: "/home/{{ current_user }}/{{ item }}"
        state: directory
      with_items:
        - .local/share/yakuake/kns_skins
    - name: fonts configuration
      shell: |
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key font "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key fixed "D2Coding ligature,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key menuFont "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key smallestReadableFont "나눔바른고딕,9,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key toolBarFont "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group WM --key activeFont "서울한강체,10,-1,5,50,0,0,0,0,0,M"
    - name: yakuake tabsonly skin install # tabsonly theme 다운로드 불가라, 미리 받아서 설치해둠
      unarchive:
        src: ~/.dotfiles/_backup/kde/yakuake/146212-tabsonly.tar.gz
        dest: ~/.local/share/yakuake/kns_skins
    - name: yakuake configuration
      shell: |
        kwriteconfig5 --file yakuakerc --group Window --key Height "100"
        kwriteconfig5 --file yakuakerc --group Window --key Width "100"
        kwriteconfig5 --file yakuakerc --group Window --key Position "100"
        kwriteconfig5 --file yakuakerc --group Window --key ShowTabBar --type boolean false
        kwriteconfig5 --file yakuakerc --group Behavior --key RememberFullscreen --type boolean true
        kwriteconfig5 --file yakuakerc --group Appearance --key Skin "tabsonly"
        kwriteconfig5 --file yakuakerc --group Appearance --key SkinInstalledWithKns --type boolean true
        kwriteconfig5 --file yakuakerc --group "Desktop Entry" --key DefaultProfile "YakuakeDefault.profile"
    - name: global shortcut keys configuration begin
      shell: |
        kquitapp5 kglobalaccel
        rm ~/.config/kglobalshortcutsrc
        cp ~/.dotfiles/_backup/kde/.config/kglobalshortcutsrc ~/.config
        kglobalaccel5 &
    - name: global etc configurations
      shell: |
        # 시작시 빈 세션으로 시작
        kwriteconfig5 --file ksmserverrc --group General --key loginMode "emptySession"
        # 터치패드 설정
        kwriteconfig5 --file touchpadxlibinputrc --group "SynPS/2 Synaptics TouchPad" --key naturalScroll --type boolean true
        kwriteconfig5 --file touchpadxlibinputrc --group "SynPS/2 Synaptics TouchPad" --key tapToClick --type boolean true
        # KDE UI의 언어를 영어로 변경
        kwriteconfig5 --file plasma-localerc --group "Translations" --key LANGUAGE "en_US:ko"
        # cursor DMZ-Black 으로 변경
        kwriteconfig5 --file kcminputrc --group "Mouse" --key cursorTheme "DMZ-Black"
