---
- name: local gnome settings
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: import dconf settings
      shell: ~/.dotfiles/_backup/gnome/load-dconfs.sh
    - name: dconf settings by cli
      shell: |
        # workspace 갯수 고정
        gsettings set org.gnome.mutter dynamic-workspaces false
        gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
        gsettings set org.gnome.desktop.wm.preferences workspace-names "['작업 공간 1', '작업 공간 2', '작업 공간 3', '작업 공간 4']"

        # 현재 작업공간에서만 애플리케이션 스위칭
        gsettings set org.gnome.shell.app-switcher current-workspace-only true
        gsettings set org.gnome.shell.window-switcher current-workspace-only true

        # Window Manager titlebar font
        gsettings set org.gnome.desktop.wm.preferences titlebar-font '한글누리 Bold 11'
    - name: ubuntu-dock settings
      shell: |
        gsettings set org.gnome.shell.extensions.dash-to-dock show-trash true
        gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style "DASHES"
        gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts true
        gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 28
        gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
        gsettings set org.gnome.shell.extensions.dash-to-dock isolate-monitors false

        # ubuntu-dock app-icon change
        mkdir -p ~/.icons/Yaru/scalable/actions
        ln -s ~/.dotfiles/_icons/ubuntu_icon_01.png ~/.icons/Yaru/scalable/actions/view-app-grid-symbolic.png
