---
- name: local dotfiles install
  hosts: 127.0.0.1, localhost
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: create base dirs # 파일 단위로만 관리하고 싶은 경우 디렉토리 미리 생성. bashrc.d 는 directory 전체 stow
      file:
        path: "/home/{{ current_user }}/{{ item }}"
        state: directory
      with_items:
        - .config
        - .local/bin
        - .local/share/applications
        - .config/nvim
        - .config/nvim-qt
        - .config/fcitx
        - .config/autostart
        - .config/copyq
        - .config/ranger
        - .config/xfce4/terminal
        - .sdkman/etc
        - Desktop
        - .vim
        - .config/.bash_it_custom
    - name: delete conflicting files
      file:
        path: "/home/{{ current_user }}/{{ item }}"
        state: absent
      with_items:
          - .sdkman/etc/config
          - .config/fcitx/conf
          - .config/fcitx/config
          - .local/share/konsole
    - name: stow
      shell: "stow -d ~/.dotfiles -t ~/ -S {{ item }}"
      with_items:
        - gnome
        - vim
        - uim
        - git
        - bashrc.d
        - bash_it_custom
        - neovim
        - sdkman
        - local_bin
        - fcitx
        - tmux
        - fusuma
        - most
        - autostart
        - copyq
        - zoom
        - mysql
        - ranger
        - xfce4-terminal
    - name: stow with adopt
      shell: "stow -d ~/.dotfiles -t ~/ --adopt -S {{ item }}"
      with_items:
        - htop
    - name: face
      file:
        path: "/home/{{ current_user }}/.face"
        src: "/home/{{ current_user }}/.dotfiles/_profiles/손권남_Time.jpg"
        state: link
        force: yes
