---
- name: local gnome settings
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: import dconf settings
      shell: ~/.dotfiles/_backup/gnome/load-dconfs.sh
    - name: dconf settings by cli
      shell: |
        # workspace 갯수 고정
        gsettings set org.gnome.mutter dynamic-workspaces false
        gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
        gsettings set org.gnome.desktop.wm.preferences workspace-names "['작업 공간 1', '작업 공간 2', '작업 공간 3', '작업 공간 4']"

        # 현재 작업공간에서만 애플리케이션 스위칭
        gsettings set org.gnome.shell.app-switcher current-workspace-only true
        gsettings set org.gnome.shell.window-switcher current-workspace-only true

        # Window Manager titlebar font
        gsettings set org.gnome.desktop.wm.preferences titlebar-font '한글누리 Bold 11'

        # 한영키, ibus 관련 설정
        gsettings set org.freedesktop.ibus.engine.hangul use-event-forwarding false
        gsettings set org.gnome.desktop.input-sources xkb-options "['korean:ralt_hangul', 'korean:rctrl_hanja']"
