---
- name: import dconf settings
  shell: ~/.dotfiles/_backup/gnome/load-dconfs.sh
- name: dconf settings by cli
  shell: |
    # workspace 갯수 고정
    gsettings set org.gnome.mutter dynamic-workspaces false
    gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
    gsettings set org.gnome.desktop.wm.preferences workspace-names "['작업 공간 1', '작업 공간 2', '작업 공간 3', '작업 공간 4']"

    # 현재 작업공간에서만 애플리케이션 스위칭
    gsettings set org.gnome.shell.app-switcher current-workspace-only true
    gsettings set org.gnome.shell.window-switcher current-workspace-only true

    # Window Manager titlebar font
    gsettings set org.gnome.desktop.wm.preferences titlebar-font '한글누리 Bold 11'
- name: ubuntu-dock settings
  shell: |
    gsettings set org.gnome.shell.extensions.dash-to-dock show-trash true
    gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style "DASHES"
    gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts true
    gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 28
    gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
    gsettings set org.gnome.shell.extensions.dash-to-dock isolate-monitors false
    gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true

    # ubuntu-dock app-icon change
    mkdir -p ~/.icons/Yaru/scalable/actions
    mkdir -p ~/.icons/Yaru/symbolic/actions
    ln -s ~/.dotfiles/_icons/ubuntu/cof_orange_hex.png ~/.icons/Yaru/scalable/actions/view-app-grid-symbolic.png
    ln -s ~/.dotfiles/_icons/ubuntu/cof_orange_hex.png ~/.icons/Yaru/symbolic/actions/view-app-grid-symbolic.png

    ln -s ~/.icons/Yaru ~/.icons/Papirus
    ln -s ~/.icons/Yaru ~/.icons/Papirus-Dark
    ln -s ~/.icons/Yaru ~/.icons/Papirus-Light
    ln -s ~/.icons/Yaru ~/.icons/Numix
    ln -s ~/.icons/Yaru ~/.icons/Numix-Circle
    ln -s ~/.icons/Yaru ~/.icons/Numix-Circle-Light
    ln -s ~/.icons/Yaru ~/.icons/Numix-Light

- name: gnome-calendar
  shell: |
    # 달력 기본 응용프로그램을 Gnome Calendar로 설정 - 텍스트 편집기로 돼 있는 버그 존재
    gio mime text/calendar org.gnome.Calendar.desktop
- name: copy templates
  shell: cp ~/.dotfiles/_backup/templates/* ~/Templates
