---
- name: import dconf settings
  shell: ~/.dotfiles/_backup/gnome/load-dconfs.sh
- name: dconf settings by cli
  shell: |
    # workspace 갯수 고정
    gsettings set org.gnome.mutter dynamic-workspaces false
    gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
    gsettings set org.gnome.desktop.wm.preferences workspace-names '["헛","둘","셋","넷"]'

    # 현재 작업공간에서만 애플리케이션 스위칭
    gsettings set org.gnome.shell.app-switcher current-workspace-only true
    gsettings set org.gnome.shell.window-switcher current-workspace-only true

    # Window Manager titlebar font
    gsettings set org.gnome.desktop.wm.preferences titlebar-font '한글누리 Bold 11'

    # Mouse 위치 찾기 켜기 - ulauncher 에서 마우스 위치찾기가 켜져있을 경우 버그가 있었으나 해결됨.
    gsettings set org.gnome.desktop.interface locate-pointer true
- name: ubuntu-dock settings
  shell: |
    gsettings set org.gnome.shell.extensions.dash-to-dock show-trash true
    gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style "DASHES"
    gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts true
    gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 28
    gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
    gsettings set org.gnome.shell.extensions.dash-to-dock isolate-monitors false
    gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true

    # ubuntu-dock app-icon change
    ~/.dotfiles/local_bin/.local/bin/set-app-grid-icon.sh ~/.dotfiles/_icons/ubuntu/cof_orange_hex.png

    # 유사 테마에 .icons override
    ln -s ~/.icons/Yaru ~/.icons/Papirus
    ln -s ~/.icons/Yaru ~/.icons/Papirus-Dark
    ln -s ~/.icons/Yaru ~/.icons/Papirus-Light
    ln -s ~/.icons/Yaru ~/.icons/Numix
    ln -s ~/.icons/Yaru ~/.icons/Numix-Circle
    ln -s ~/.icons/Yaru ~/.icons/Numix-Circle-Light
    ln -s ~/.icons/Yaru ~/.icons/Numix-Light

- name: gnome-calendar
  shell: |
    # 달력 기본 응용프로그램을 Gnome Calendar로 설정 - 텍스트 편집기로 돼 있는 버그 존재
    # gnome-calendar install required
    gio mime text/calendar org.gnome.Calendar.desktop
