---
- name: local user application install
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: create jdk dir
      file:
        path: ~/.local/opt/jdk
        state: directory
    - name: adopt open jdks
      unarchive:
        src: "{{ item }}"
        remote_src: yes
        dest: "/home/{{current_user}}/.local/opt/jdk"
      register: adoptopenjdk_installed
      until: adoptopenjdk_installed is not failed
      retries: 3
      delay: 10
      with_items:
        - "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9%2B11.1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.9_11.tar.gz"
        - "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u272-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u272b10.tar.gz"
        - "https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz"
    - name: register jenv
      shell: |
        export PATH="$HOME/.jenv/bin:$PATH"
        eval "$(jenv init -)"
        for jdk in ~/.local/opt/jdk/*; do
          if [[ -d $jdk ]]
          then
            echo "add to jenv $jdk"
            jenv add $jdk
          fi
        done
      args:
        executable: /usr/bin/bash
