---
- name: KDE local user configuration
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: fonts configuration
      shell: |
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key font "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key fixed "D2Coding ligature,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key menuFont "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key smallestReadableFont "나눔바른고딕,9,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key toolBarFont "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group WM --key activeFont "서울한강체,10,-1,5,50,0,0,0,0,0,M"
