---
- name: local dotfiles install
  hosts: 127.0.0.1, localhost
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: create base dirs # 파일 단위로만 관리하고 싶은 경우 디렉토리 미리 생성
      file:
        path: "/home/{{ current_user }}/{{ item }}"
        state: directory
      with_items:
        - "{{ local_bashrcs_dir }}"
        - .config/copyq
        - .local/bin
        - .config/nvim
        - .config/nvim-qt
        - .sdkman/etc
    - name: delete conflicting files
      file:
        path: "/home/{{ current_user }}/{{ item }}"
        state: absent
      with_items:
          - .sdkman/etc/config
    - name: stow
      shell: "stow -d ~/.dotfiles -t ~/ -S {{ item }}"
      with_items:
        - vim
        - uim
        - htop
        - git
        - bashrc.d
        - copyq
        - neovim
        - sdkman
        - local_bin
    - name: after dotfiles install
      shell: |
        # vim plugin install
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        # PlugInstall then quit - redirect 가 없으면 올바로 작동안함. colorscheme 설정에도 silent! 필요.
        # https://github.com/junegunn/vim-plug/issues/730
        vim +'PlugInstall --sync' +qa &> /dev/null < /dev/tty
