---
- name: KDE local user configuration
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: fonts configuration
      shell: |
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key font "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key fixed "D2Coding ligature,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key menuFont "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key smallestReadableFont "나눔바른고딕,9,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group General --key toolBarFont "나눔바른고딕,11,-1,5,50,0,0,0,0,0"
        kwriteconfig5 --file ~/.config/kdeglobals --group WM --key activeFont "서울한강체,10,-1,5,50,0,0,0,0,0,M"
    - name: yakuake tabsonly skin install
      unarchive:
        src: https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE0NjQ4MDM1NzEiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6ImI1YzZlNjJhNWE1MjljMDgwZjdmZGJmZDBlZmE0NWJhMTdiZjBlN2UyMTYxMzNjYjZiZmFiMmI2OTAzODE3MzkyM2UyNjM4MjVlOWI1YjYyZDgwY2ZjNjkxMDI4NTZlNWM1MjkzNzMyMTZjMzFiZTk5MDljZDY4ZDk3MzYyMjdhIiwidCI6MTYwMDkwMDExNywic3RmcCI6IjNkNmVmNzkxNGQzOTQ4NjFjNTFlNGZiZGE1ZGY0OTFjIiwic3RpcCI6IjE0LjM1LjIyOS4zMSJ9.h5D2BXSuSYLnglqPLzC_YA49pnnXA-4TVIf5lPFYwog/146212-tabsonly.tar.gz
        dest: ~/.local/share/yakuake/kns_skins
        remote_src: yes
      register: tabsonly_downloaded
      until: tabsonly_downloaded is not failed
      retries: 3
    - name: yakuake configuration
      shell: |
        kwriteconfig5 --file yakuakerc --group Window --key Height "100"
        kwriteconfig5 --file yakuakerc --group Window --key Width "100"
        kwriteconfig5 --file yakuakerc --group Window --key Position "100"
        kwriteconfig5 --file yakuakerc --group Window --key ShowTabBar --type boolean false
        kwriteconfig5 --file yakuakerc --group Behavior --key RememberFullscreen --type boolean true
        kwriteconfig5 --file yakuakerc --group Appearance --key Skin "tabsonly"
        kwriteconfig5 --file yakuakerc --group Appearance --key SkinInstalledWithKns --type boolean true
        kwriteconfig5 --file yakuakerc --group "Desktop Entry" --key DefaultProfile "YakuakeDefault.profile"
    - name: global shortcut keys configuration begin
      shell: |
        kquitapp5 kglobalaccel
        rm ~/.config/kglobalshortcutsrc
        cp ~/.dotfiles/_backup/kde/.config/kglobalshortcutsrc ~/.config
        kglobalaccel5 &
    - name: global etc configurations
      shell: |
        # 시작시 빈 세션으로 시작
        kwriteconfig5 --file ksmserverrc --group General --key loginMode "emptySession"
        # 터치패드 설정
        kwriteconfig5 --file touchpadxlibinputrc --group "SynPS/2 Synaptics TouchPad" --key naturalScroll --type boolean true
        kwriteconfig5 --file touchpadxlibinputrc --group "SynPS/2 Synaptics TouchPad" --key tapToClick --type boolean true
        # KDE UI의 언어를 영어로 변경
        # kwriteconfig5 --file plasma-localerc --group "Translations" --key LANGUAGE "en_US:ko"

