---
- name: create jdk dir
  file:
    path: ~/.local/opt/jdk
    state: directory
- name: temurin open jdks
  ansible.builtin.unarchive:
    src: "{{ item }}"
    remote_src: yes
    dest: "/home/{{current_user}}/.local/opt/jdk"
    validate_certs: no
  register: temurinopenjdk_installed
  until: temurinopenjdk_installed is not failed
  retries: 3
  delay: 10
  with_items:
    - "https://api.adoptium.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"
    - "https://api.adoptium.net/v3/binary/latest/11/ga/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"
    - "https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/adoptium?project=jdk"
- name: register jenv
  shell: |
    export PATH="$HOME/.jenv/bin:$PATH"
    eval "$(jenv init -)"
    for jdk in ~/.local/opt/jdk/*; do
      if [[ -d $jdk ]]
      then
        echo "add to jenv $jdk"
        jenv add $jdk
      fi
    done
    # add system openjdk
    jenv add /usr/lib/jvm/java-11-openjdk-amd64
  args:
    executable: /usr/bin/bash
