---
- name: main
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/home/linuxbrew/.linuxbrew/bin"
  tasks:
    - import_tasks: prepare_system_env_tasks.yml
    - import_tasks: package_repos_tasks.yml
    - import_tasks: common_package_install_tasks.yml
    - import_tasks: docker_install_tasks.yml
    - import_tasks: gnome_package_install_tasks.yml
    - import_tasks: prepare_user_dirs_tasks.yml
    - import_tasks: development_package_install_tasks.yml
    - import_tasks: homebrew_install_playbook.yml
    - import_tasks: package_full_upgrade_tasks.yml
    - import_tasks: free_korean_fonts_install_tasks.yml
    - import_tasks: firewall_config_tasks.yml
    - import_tasks: local_apps_install_tasks.yml
    - import_tasks: fusuma_install_tasks.yml
    - import_tasks: local_dotfiles_install_tasks.yml
    - import_tasks: local_gnome_configs_tasks.yml
    - import_tasks: grub_themes_install_tasks.yml
    - import_tasks: local_develop_env_tasks.yml
    - import_tasks: keep_usb_tethering_tasks.yml
    - import_tasks: backup_tasks.yml
    - import_tasks: add_crons.yml
    - import_tasks: nvidia_screen_tearing_fix.yml
    #- import_tasks: auto_cpufreq_tasks.yml
    #- import_tasks: sound_theme_tasks.yml # 22.10 부터 override 불필요해진듯.
