---
- name: meganz package installation
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: download meganz
      become: yes
      apt:
        deb: "{{ item }}"
      register: meganz_debs_installed
      until: meganz_debs_installed is not failed
      retries: 3
      delay: 10
      with_items:
        - "https://mega.nz/linux/MEGAsync/xUbuntu_{{ ubuntu_version }}/amd64/megacmd-xUbuntu_{{ ubuntu_version }}_amd64.deb"
        - "https://mega.nz/linux/MEGAsync/xUbuntu_{{ ubuntu_version }}/amd64/megasync-xUbuntu_{{ ubuntu_version }}_amd64.deb"
