---
# nvidia option 은 nvidia가아니면 아무 영향을 안끼침
- name: nvidia screen-tearing fix
  become: yes
  ansible.builtin.file:
    src: "/home/{{ current_user }}/.dotfiles/_backup/nvidia/99-nvidia-myoptions.conf"
    dest: "/etc/X11/xorg.conf.d/99-nvidia-myoptions.conf"
    state: link
