---
- name: prepare system environment
  hosts: 127.0.0.1, localhost
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: xanmod kernel key
      become: yes
      apt_key:
        url: https://dl.xanmod.org/gpg.key
      register: xanmod_kernal_key_installed
      until: xanmod_kernal_key_installed is not failed
      retries: 3
    - name: xanmod kernel repo
      become: yes
      apt_repository:
        repo: deb http://deb.xanmod.org releases main
        filename: xanmod-kernel
        update_cache: no
    - name: vivaldi browser key
      become: yes
      apt_key:
        url: https://repo.vivaldi.com/archive/linux_signing_key.pub
      register: vivaldi_key_installed
      until: vivaldi_key_installed is not failed
      retries: 3
    - name: vivaldi browser repo
      become: yes
      apt_repository:
        repo: deb https://repo.vivaldi.com/archive/deb/ stable main
        filename: vivaldi
        update_cache: no
    - name: virtualbox key
      become: yes
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      register: virtualbox_key_installed
      until: virtualbox_key_installed is not failed
      retries: 3
    - name: virtualbox repo
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ubuntu_release }} contrib"
        filename: virtualbox
        update_cache: no
    - name: github cli key
      become: yes
      apt_key:
        id: C99B11DEB97541F0
        keyserver: keyserver.ubuntu.com
    - name: github cli repo
      become: yes
      apt_repository:
        repo: "deb https://cli.github.com/packages {{ ubuntu_release }} main"
        filename: github-cli
        update_cache: no
    - name: hashicorp key
      become: yes
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
      register: hashicorp_key_installed
      until: hashicorp_key_installed is not failed
      retries: 3
    - name: hashicorp repo
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_release }} main"
        filename: hashicorp
        update_cache: no
    - name: typora key
      become: yes
      apt_key:
        url: https://typora.io/linux/public-key.asc
      register: typora_key_installed
      until: typora_key_installed is not failed
      retries: 3
    - name: typora repo
      become: yes
      apt_repository:
        repo: deb https://typora.io/linux ./
        filename: typora
        update_cache: no
    - name: add PPAs
      become: yes
      shell: "add-apt-repository -y --no-update {{ item }}"
      with_items:
        - ppa:jonathonf/vim
        - ppa:gezakovacs/ppa
        - ppa:git-core/ppa
        - ppa:graphics-drivers/ppa
        - ppa:linrunner/tlp
        - ppa:linuxuprising/apps
        - ppa:kdenlive/kdenlive-stable
        - ppa:neovim-ppa/stable
        - ppa:kritalime/ppa
        - ppa:papirus/papirus
        - ppa:qbittorrent-team/qbittorrent-stable
        - ppa:hluk/copyq
    - name: multiverse universe
      become: yes
      shell: "apt-add-repository -y --no-update {{ item }}"
      with_items:
        - multiverse
        - universe
          #- name: asbru-cm
          #become: yes
          #shell: curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | bash
          #args:
          #creates: /etc/apt/sources.list.d/asbru-cm_asbru-cm.list
    - name: update apt cache all
      become: yes
      apt:
        update_cache: yes
    - name: remove snapd
      become: yes
      shell: |
        apt purge -y --autoremove snapd
        rm -rf /snap
        rm -rf /var/snap
        rm -rf /var/lib/snapd
        rm -rf /var/cache/snapd
