---
- name: docker key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
  register: docker_key_installed
  until: docker_key_installed is not failed
  retries: 3
- name: docker repository # docker repository는 Ubuntu release 후 10일 이상 지나야 추가되는 편임.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable"
    filename: docker
    update_cache: no
- name: vivaldi browser key
  become: yes
  ansible.builtin.apt_key:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
  register: vivaldi_key_installed
  until: vivaldi_key_installed is not failed
  retries: 3
- name: vivaldi browser repo
  become: yes
  apt_repository:
    repo: deb https://repo.vivaldi.com/archive/deb/ stable main
    filename: vivaldi
    update_cache: no
- name: vscode key
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
  register: vscode_key_installed
  until: vscode_key_installed is not failed
  retries: 3
- name: vscode repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
    update_cache: no
- name: hashicorp key
  become: yes
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
  register: hashicorp_key_installed
  until: hashicorp_key_installed is not failed
  retries: 3
- name: hashicorp repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_release }} main"
    filename: hashicorp
    update_cache: no
- name: typora key
  become: yes
  ansible.builtin.apt_key:
    url: https://typora.io/linux/public-key.asc
  register: typora_key_installed
  until: typora_key_installed is not failed
  retries: 3
- name: typora repository
  become: yes
  apt_repository:
    repo: "deb https://typora.io/linux ./"
    filename: typora
    update_cache: no
- name: add PPAs
  become: yes
  shell: "add-apt-repository -y --no-update {{ item }}"
  with_items:
    - ppa:git-core/ppa
    - ppa:graphics-drivers/ppa
    - ppa:papirus/papirus
    - ppa:cappelikan/ppa # for mainline
- name: multiverse universe
  become: yes
  shell: "apt-add-repository -y --no-update {{ item }}"
  with_items:
    - multiverse
    - universe
- name: update apt cache all
  become: yes
  apt:
    update_cache: yes
    upgrade: full
