---
- name: prepare system environment
  hosts: 127.0.0.1, localhost
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: vivaldi browser key
      become: yes
      apt_key:
        url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    - name: vivaldi browser repo
      become: yes
      apt_repository:
        repo: deb https://repo.vivaldi.com/archive/deb/ stable main
        filename: vivaldi
        update_cache: no
    - name: virtualbox key
      become: yes
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - name: virtualbox repo
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ubuntu_release }} contrib"
        filename: virtualbox
        update_cache: no
    - name: vscode key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
    - name: vscode repo
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: vscode
        update_cache: no
    - name: typora key
      become: yes
      apt_key:
        url: https://typora.io/linux/public-key.asc
    - name: typora repo
      become: yes
      apt_repository:
        repo: deb https://typora.io/linux ./
        filename: typora
        update_cache: no
    - name: add PPAs
      become: yes
      shell: "add-apt-repository -y --no-update {{ item }}"
      with_items:
        - ppa:jonathonf/vim
        - ppa:gezakovacs/ppa
        - ppa:git-core/ppa
        - ppa:graphics-drivers/ppa
        - ppa:linrunner/tlp
        - ppa:linuxuprising/apps
        - ppa:pinta-maintainers/pinta-stable
        - ppa:kdenlive/kdenlive-stable
        - ppa:neovim-ppa/stable
    - name: multiverse universe
      become: yes
      shell: "apt-add-repository -y --no-update {{ item }}"
      with_items:
        - multiverse
        - universe
    - name: asbru-cm
      become: yes
      shell: curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | bash
      args:
        creates: /etc/apt/sources.list.d/asbru-cm_asbru-cm.list
    - name: update apt cache all
      become: yes
      apt:
        update_cache: yes
