---
- name: docker repository
  become: yes
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: yes
  register: docker_repository_installed
  until: docker_repository_installed is not failed
  retries: 3
- name: vscode repository
  become: yes
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  register: vscode_repository_installed
  until: vscode_repository_installed is not failed
  retries: 3
- name: add PPAs
  become: yes
  shell: "add-apt-repository -y --no-update {{ item }}"
  with_items:
    - ppa:git-core/ppa
    - ppa:cappelikan/ppa # for mainline
    - ppa:danielrichter2007/grub-customizer
    - ppa:ubuntuhandbook1/annotator
    #- ppa:graphics-drivers/ppa # 최신 nvidia driver 가 굳이 필요해보이지는 않아서 일단 disable
- name: multiverse universe
  become: yes
  shell: "apt-add-repository -y --no-update {{ item }}"
  with_items:
    - multiverse
    - universe
- name: update apt cache all
  become: yes
  apt:
    update_cache: yes
    upgrade: full
