---
- name: prepare system environment
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "vars.yml"
  tasks:
    - name: add to sudoers
      become: yes
      copy:
        dest: "/etc/sudoers.d/99-self"
        content: "{{ current_user }}    ALL=(ALL:ALL) NOPASSWD: ALL"
        mode: 0440
        owner: root
        group: root
    - name: change swappiness
      become: yes
      copy:
        dest: "/etc/sysctl.d/99-vm-swappiness.conf"
        content: "vm.swappiness=5"
        owner: root
        group: root
    - name: change ubuntu mirror to kakao
      become: yes
      replace:
        path: "/etc/apt/sources.list"
        regexp: "http:\/\/kr.archive.ubuntu.com/"
        replace: "http:\/\/mirror.kakao.com/"
    - name: update ubuntu mirror
      become: yes
      apt:
        update_cache: yes
    - name: install basically required packages
      become: yes
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - software-properties-gtk
          - unzip
          - unrar
          - p7zip-full
          - curl
        autoclean: yes
