---
- name: Yaru sound theme local dir
  ansible.builtin.file:
    path: "/home/{{ current_user }}/.local/share/sounds/Yaru/stereo"
    state: directory
- name: Yaru sound theme alarm-clock-elapsed override # 기본 알람 소리가 너무 시끄러워서 변경함
  ansible.builtin.file:
    src: /usr/share/sounds/gnome/default/alerts/glass.ogg
    dest: "/home/{{ current_user }}/.local/share/sounds/Yaru/stereo/alarm-clock-elapsed.ogg"
    state: link
- name: sound theme change to Yaru
  shell: |
    gsettings set org.gnome.desktop.sound theme-name "Yaru"
    gsettings set org.gnome.desktop.sound input-feedback-sounds true
    gsettings set org.gnome.desktop.sound event-sounds true
